# -*- coding: utf-8 -*-
"""Tic Tac Toe(Player vs Player).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1thGBC2tp3pNH0_8kkFWHUCENMaLHXOma
"""

board={'7': ' ' ,  '8': ' ' , '9': ' ',
       '4': ' ' ,  '5':' '  ,  '6': ' ',
       '1': ' ' ,  '2': ' ' , '3': ' '}
board_keys=[]
for key in board:
    board_keys.append(key)

def printBoard(board):
    print(board['7'] + '|' + board['8'] + '|' + board['9'])
    print('-+-+-')
    print(board['4'] + '|' + board['5'] + '|' + board['6'])
    print('-+-+-')
    print(board['1'] + '|' + board['2'] + '|' + board['3'])

print('X:HUMAN PLAYER')
print('0: COMPUTER')

import random as rand
def game():
    turn='X'
    count=0
    for key in board_keys:
      board[key]=' '
  
    for i in range(10):
        printBoard(board)
        print('It is your turn, ' + turn + '.Move to which place?')
        if(turn=='X'):
          move=input()
          if move not in board.keys():
            print('InCorrect Move Please enter the correct move')
            continue
        else:
          move=rand.randrange(1,10)    
          move=str(move)
        if board[move]==' ':
            board[move]=turn
            count+=1
        else:
            print('The place is alredy filled,\n Move to which place?')
            continue
        if(count>=5):
            if board['7']==board['8']==board['9']!=' ':
                printBoard(board)
                print('\nGame Over.\n')
                print(" ****** " + turn + "  Won. *****")
                break
            elif board['4']==board['5']==board['6']!=' ':
                printBoard(board)
                print('\nGamr Over\n')
                print(" ****** " + turn + "  Won. *****")
                break
            elif board['1']==board['2']==board['3']!=' ':
                printBoard(board)
                print('\nGamr Over\n')
                print(" ****** " + turn + "  Won. *****")
                break
            elif board['1']==board['4']==board['7']!=' ':
                printBoard(board)
                print('\nGamr Over\n')
                print(" ****** " + turn + "  Won. *****")
                break
            elif board['2']==board['5']==board['8']!=' ':
                printBoard(board)
                print('\nGamr Over\n')
                print(" ****** " + turn + "  Won. *****")
                break
            elif board['3']==board['6']==board['9']!=' ':
                printBoard(board)
                print('\nGamr Over\n')
                print(" ****** " + turn + "  Won. *****")
                break
            elif board['7']==board['5']==board['3']!= ' ':
                printBoard(board)
                print('\nGamr Over\n')
                print(" ****** " + turn + "  Won. *****")
                break
            elif board['1']==board['5']==board['9']!=' ':
                printBoard(board)
                print("\nGamr Over\n")
                print(" ****** " + turn + "  Won. *****")
                break   
        if count==9:
            print('\nGame Over.\n')
            print('It is tie!')

        if turn=='X':
            turn='0'
        else:
            turn='X'
    restart=input('Do You Want to play Again ? (y/n)')
    if restart=='y' or restart=='Y':
        for key in board_keys:
            board[key]==' '
        game()



game()

